### ISSUE TITLE
Todo following Code Camp

### ISSUE THREAD

**Issue by nikostr** [zetkin/team-datasci#1]
- [ ] Verify mapping between DeSO areas and valdistrikt, including potential weighting of valdistrikt stats
- [ ] Descriptive info pipeline
- [ ] Interactive visualizations of stats, maps of interest
- [ ] Heterogeneity analysis for phone canvasing
- [ ] Easily update-able standardized analyses and reports
- [ ] Add dummy files containing fake call data
